# Generated by Django 5.0.4 on 2024-04-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30, null=True)),
                ('rollno', models.TextField(max_length=30)),
                ('enrlno', models.TextField(max_length=20, null=True)),
            ],
        ),
    ]
