# Generated by Django 5.0.4 on 2024-05-03 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_course_student_desc_student_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='insta',
        ),
    ]
