# Generated by Django 5.0.4 on 2024-05-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.TextField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
