# Generated by Django 5.0.4 on 2024-05-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_student_course_student_desc_student_github_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.TextField(default='MCA', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.TextField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to='photo/'),
        ),
    ]
