# Generated by Django 5.0.4 on 2024-05-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_student_course_alter_student_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='link',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='twitter',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
