# Generated by Django 5.0.4 on 2024-05-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_student_course_alter_student_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='projects',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.TextField(default='MCA', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.TextField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrlno',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='github',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to='photo/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='link',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='linkedin',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.TextField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='twitter',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
