# Generated by Django 5.0.4 on 2024-06-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_student_projects_alter_student_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='leetcode',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='projects',
            field=models.JSONField(null=True),
        ),
    ]
