# Generated by Django 4.1.13 on 2024-06-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_student_leetcode_alter_student_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('company', models.TextField(null=True)),
                ('desc', models.TextField(null=True)),
                ('link', models.TextField(null=True)),
            ],
        ),
    ]
