# Generated by Django 4.1.13 on 2024-06-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='qualification',
            field=models.TextField(null=True),
        ),
    ]
