# Generated by Django 4.1.13 on 2024-06-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_job_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='remote',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='worktype',
            field=models.TextField(null=True),
        ),
    ]
