# Generated by Django 4.1.13 on 2024-06-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_job_remote_job_worktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='remote',
            field=models.TextField(null=True),
        ),
    ]
